# -*- coding: utf-8 -*-
"""Lab 3 - Plotting_iteration_roundoff.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GcyRrYE9mkbVVcKMu67SYQl1T7sda7u

#**Lab 3 - Plotting, iteration, and roundoff error**

Enter your code in the spaces provided. Do not change any of the variable names or function names that are already provided for you. In places where we specify the name of the return value, make sure that your code produces the a value with the correct name.
"""

# Do not edit this cell.

LabID="Lab3"

try:
  from graderHelp import ISGRADEPLOT
except ImportError:
  ISGRADEPLOT = True

"""**Enter your BYU NetID**"""

# Enter your first and last names in between the quotation marks.

first_name="Your first name goes here"

last_name="Your last name goes here"

# Enter your Math 215 section number in between the quotation marks. 

section_number="Your Math 215 section number goes here"  

# Enter your BYU NetID in between the quotation marks.  NOT YOUR BYU ID NUMBER! 

BYUNetID="Your BYU NetID goes here"

"""**Import NumPy and PyPlot**"""

import numpy as np
from matplotlib import pyplot as plt

"""**Problem 1**"""

# Plot both functions from Problem 1 here.  Put all of your code to create the plot inside the function below.

def create_plots():
  # Put all of your code to create the plot here.
  return None

"""**Problem 2**"""

# Create the scatter plot from Problem 2 here.  Put all of your code to create the plot inside the function below.

def create_scatter_plot():
  # Put all of your code to create the scatter plot here.
  return None

"""**Problem 3**"""

def fact(n):
  if n==0:
    return # Place the first part of your code here.
  else:
    return # Place the remaining part of your code here.

"""**Problem 4**"""

root = -1 # Replace the value -1 with your approximation to the root of f(x), correct to 12 decimal places.

"""**Problem 5**"""

def g(x):
  return # Put your return value, i.e. the value of g(x), here.

def g_prime(x):
  return # Put your return value, i.e. the value of the derivative g'(x), here.

"""**Problem 6**"""

def newtons_method(starting_guess,n):
  # Put your code here.
  return # Put your return value here.

"""**Problem 7**"""

def integration(m):
  # Put your code here.
  return # Put your return value here.

"""**STOP!  BEFORE YOU SUBMIT THIS LAB:**  Go to the "Runtime" menu at the top of this page, and select "Restart and run all".  If any of the cells produce error messages, you will either need to fix the error(s) or delete the code that is causing the error(s).  Then use "Restart and run all" again to see if there are any new errors.  Repeat this until no new error messages show up.

**You are not ready to submit until you are able to select "Restart and run all" without any new error messages showing up.  Your code will not be able to be graded if there are any error messages.**

To submit your lab for grading you must first download it to your compute as .py file. In the "File" menu select "Download .py". The resulting file can then be uploaded to http://www.math.byu.edu:30000 for grading.
"""